flats:
  - name: "Cozy Cottage"
    description: "From the outside this house looks gorgeous. It has been built with walnut wood and has walnut wood decorations. Tall, rounded windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.

The house is equipped with a modern kitchen and two bathrooms, it also has a spacious living room, four bedrooms, a large dining area, a study and a large garage.

The building is shaped like a short U. The two extensions extend into glass overhanging panels to each side.
The second floor is bigger than the first, which creates a stylish overhang around half the house. This floor has a different style than the floor below.

The roof is low and pyramid shaped and is covered with grey roof tiles. One small chimney pokes out the center of the roof. Rows of small windows let in plenty of light to the rooms below the roof.
The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot."
  - name: "Modern Loft"
    description: "
From the outside this house looks old, but wonderful. It has been built with grey bricks and has yellow pine wooden decorations. Small, half rounded windows brighten up the house and have been added to the house in a fairly symmetrical pattern.

The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, three bedrooms, a roomy dining room, a bar and a large storage room.

The building is shaped like an L. The extension extends into glass overhanging panels circling around half the house.
The second floor is bigger than the first, which creates several overhanging parts on one side of the house. This floor has a different style than the floor below.

The roof is flat and is covered with black ceramic tiles. Two large chimneys sit at the side of the house. Several small windows let in just enough light to the rooms below the roof.
The house itself is surrounded by a gorgeous garden with many hidden lights that make the garden come to life at night."
  - name: "Silion"
    description: "From the outside this house looks nice and traditional. It has been built with fir wood and has poplar wooden decorations. Tall, wide windows allow enough light to enter the home and have been added to the house in a fairly symmetrical pattern.

The house is equipped with a small kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a cozy storage room.

The building is shaped like an L. The extension extends into a garden path circling around half the house.
The second floor is bigger than the first, which creates several overhanging parts on one side of the house. This floor has roughly the same style as the floor below.

The roof is high and v-shaped and is covered with stone slabs. One small chimney pokes out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.
The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers."
  - name: "Woo Flower"
    description: "From the outside this house looks gorgeous. It has been built with brown bricks and has mahogany wooden decorations. Tall, wide windows add to the overall look of the house and have been added to the house in a very symmetric way.

The house is equipped with a modern kitchen and one modern bathroom, it also has a large living room, three bedrooms, a small dining room, a sun room and a cozy basement.

The building is shaped like an L. The extension extends into glass overhanging panels circling around half the house.
The second floor is smaller than the first, which allowed for a large balcony on one side of the house. This floor follows the same style as the floor below.

The roof is flat and is covered with dark ceramic tiles. One small chimney sits at the side of the house. There are no windows on the roof.
The house itself is surrounded by a gorgeous garden, including various trees, bushes, flowers and a large pond."
  - name: "Croudo Flower"
    description: "From the outside this house looks snug and comfortable. It has been built with walnut wood and has white pine wooden decorations. Tall, squared windows let in plenty of light and have been added to the house in a very asymmetric way.

The house is equipped with a huge kitchen and one average bathroom, it also has a snug living room, four bedrooms, a spacious dining room and a cozy basement.

The building is shaped like a circle. The house is fully surrounded by wooden overhanging panels.
The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has a slightly different style than the floor below.

The roof is high and triangular and is covered with brown wood shingles. Two large chimneys poke out the center of the roof. Several large windows let in plenty of light to the rooms below the roof.
The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers."
  - name: "Hogrungin"
    description: "
From the outside this house looks impressive. It has been built with fir wood and has tan brick decorations. Tall, large windows add to the overall style of the house and have been added to the house in a very asymmetric way.

The house is equipped with a small kitchen and one modern bathroom, it also has a small living room, three bedrooms, a small dining area and a large storage room.

The building is shaped like a T. The two extensions are linked by overgrown wooden overhanging panels circling around half the house.
The second floor is the same size as the first, but part of it hangs over the edge of the floor below, creating an overhang on one side and a balcony on the other. This floor has a slightly different style than the floor below.

The roof is high and slanted to one side and is covered with brown ceramic tiles. Two small chimneys sit at either side of the house. There are no windows on the roof.
The house itself is surrounded by a gorgeous garden with many hidden lights that make the garden come to life at night."
  - name: "Zeomonelo"
    description: "From the outside this house looks luxurious. It has been built with white bricks and has walnut wood decorations. Short, wide windows allow enough light to enter the home and have been added to the house in a very asymmetric way.

The house is equipped with an old-fashioned kitchen and three bathrooms, it also has a huge living room, three bedrooms, a small dining area and a snug storage room.

The building is fairly rounded in shape. The house is half surrounded by glass overhanging panels.
The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor follows the same style as the floor below.

The roof is low and v-shaped and is covered with flat roof tiles. Two small chimneys poke out the center of the roof. There are no windows on the roof.
The house itself is surrounded by paved ground, with various party spots, like a fancy barbeque and a firepit."
  - name: "Drake Collard"
    description: "
From the outside this house looks posh and extravagant. It has been built with burgandy bricks and has white brick decorations. Short, wide windows add to the overall style of the house and have been added to the house in a mostly symmetric way.

The house is equipped with a huge kitchen and one average bathroom, it also has a large living room, four bedrooms, a roomy dining area, a lounge area and a large basement.

The building is shaped like a circle. The house is fully surrounded by a covered patio.
The second floor is smaller than the first, which creates a layered style of look in combination with the roof. This floor follows the same style as the floor below.

The roof is high and triangular and is covered with black roof tiles. One large chimney pokes out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.
The house itself is surrounded by a modest garden, with mostly grass and a few small trees"
  - name: "Winter Hop"
    description: "From the outside this house looks nice and traditional. It has been built with poplar wood and has red brick decorations. Small, rounded windows add to the overall look of the house and have been added to the house in a fairly symmetrical pattern.

The house is equipped with an average kitchen and one large bathroom, it also has a snug living room, five bedrooms, a roomy dining room, a study and a spacious storage room.

The building is shaped like an L. The extension extends into wooden overhanging panels circling around half the house.
The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has a different style than the floor below.

The roof is high and square shaped and is covered with slate shingles. Two large chimneys sit at the side of the house. Several small windows let in just enough light to the rooms below the roof.
The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot."
  - name: "Devil Cabbage"
    description: "From the outside this house looks gorgeous. It has been built with bricks covered in render and has sandstone decorations. Large, triangular windows let in plenty of light and have been added to the house in a mostly symmetric way.

The house is equipped with an average kitchen and one modern bathroom, it also has a snug living room, five bedrooms, a large dining room, a sun room and a spacious garage.

The building is fairly rounded in shape. The house is half surrounded by glass overhanging panels.
The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.

The roof is high and pyramid shaped and is covered with brown ceramic tiles. One large chimney pokes out the center of the roof. There are no windows on the roof.
The house itself is surrounded by a modest, childsafe garden covered mostly in grass and with a children's playground in the center."
  - name: "Mellow Cress"
    description: "From the outside this house looks very elegant. It has been built with wheat colored bricks and has poplar wooden decorations. Large, triangular windows add to the overall style of the house and have been added to the house in a mostly symmetric way.

The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, two bedrooms, a spacious dining area, a playroom and a large basement.

The building is shaped like an L. The extension extends into a garden path reaching until the end of that side of the house.
The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.

The roof is high and rounded and is covered with red wood shingles. One large chimney pokes out the center of the roof. Two roof terraces let in plenty of light to the rooms below the roof.
The house itself is surrounded by a modest, childsafe garden covered mostly in grass and with a children's playground in the center."
  - name: "Silk Rice"
    description: "
From the outside this house looks warm and cozy. It has been built with white pine wood and has brown brick decorations. Small, rectangular windows brighten up the house and have been added to the house in a mostly asymmetric way.

The house is equipped with an old-fashioned kitchen and one small bathroom, it also has a warm living room, three bedrooms, a roomy dining area and a small basement.

The building is rectangular shaped. The house is fully surrounded by stylish gardens.
The second floor is bigger than the first, which creates several overhanging parts on one side of the house. This floor follows the same style as the floor below.

The roof is low and triangular and is covered with grey roof tiles. One small chimney pokes out the center of the roof. Several long, thin windows let in plenty of light to the rooms below the roof.
The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot."
