parises:
  - name: " Louise"
    address: "1881 Rue Royale, 75008 Paris, France"
    description: "From the outside this house looks gorgeous. It has been built with walnut wood and has walnut wood decorations. Tall, rounded windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.

The house is equipped with a modern kitchen and two bathrooms, it also has a spacious living room, four bedrooms, a large dining area, a study and a large garage.

The building is shaped like a short U. The two extensions extend into glass overhanging panels to each side.
The second floor is bigger than the first, which creates a stylish overhang around half the house. This floor has a different style than the floor below.

The roof is low and pyramid shaped and is covered with grey roof tiles. One small chimney pokes out the center of the roof. Rows of small windows let in plenty of light to the rooms below the roof.
The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot."
  - name: " Jules"
    address: "1881 Rue Royale, 75008 Paris, France"

    description: "
From the outside this house looks old, but wonderful. It has been built with grey bricks and has yellow pine wooden decorations. Small, half rounded windows brighten up the house and have been added to the house in a fairly symmetrical pattern.

The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, three bedrooms, a roomy dining room, a bar and a large storage room.

The building is shaped like an L. The extension extends into glass overhanging panels circling around half the house.
The second floor is bigger than the first, which creates several overhanging parts on one side of the house. This floor has a different style than the floor below.

The roof is flat and is covered with black ceramic tiles. Two large chimneys sit at the side of the house. Several small windows let in just enough light to the rooms below the roof.
The house itself is surrounded by a gorgeous garden with many hidden lights that make the garden come to life at night."
  - name: "SBastien"
    address: "1881 Rue Royale, 75008 Paris, France"

    description: "From the outside this house looks nice and traditional. It has been built with fir wood and has poplar wooden decorations. Tall, wide windows allow enough light to enter the home and have been added to the house in a fairly symmetrical pattern.

The house is equipped with a small kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a cozy storage room.

The building is shaped like an L. The extension extends into a garden path circling around half the house.
The second floor is bigger than the first, which creates several overhanging parts on one side of the house. This floor has roughly the same style as the floor below.

The roof is high and v-shaped and is covered with stone slabs. One small chimney pokes out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.
The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers."
  - name: "Woo Flower"
    description: "From the outside this house looks gorgeous. It has been built with brown bricks and has mahogany wooden decorations. Tall, wide windows add to the overall look of the house and have been added to the house in a very symmetric way.

The house is equipped with a modern kitchen and one modern bathroom, it also has a large living room, three bedrooms, a small dining room, a sun room and a cozy basement.

The building is shaped like an L. The extension extends into glass overhanging panels circling around half the house.
The second floor is smaller than the first, which allowed for a large balcony on one side of the house. This floor follows the same style as the floor below.

The roof is flat and is covered with dark ceramic tiles. One small chimney sits at the side of the house. There are no windows on the roof.
The house itself is surrounded by a gorgeous garden, including various trees, bushes, flowers and a large pond."
